### PR TITLE
Custom elements fix

### PR DESCRIPTION
**Pull request by jakubknejzlik**
When trying running as .Central I've found that the CustomElements overridden init method wasn't public, making it impossible to initialize from another module.

### CODE REVIEW

**Comment by robreuss** [comment]
Thanks.  I don't have much experience with pull requests.  Should I use the Github feature to automatically merge, thereby bringing your podspec in, and then update that to point to my repository?  Or should I just merge the CustomElements change via the command line?

**Comment by jakubknejzlik** [comment]
Didn't try it from the command line (also I'm not sure, if it's possible from command line to accept pull request)...github worked fine for me in all cases.

**Comment by jakubknejzlik** [comment]
Ouch, my bad! I've watched the commited changes again, and it contains edits from another commit (cocoapods pull request). I'll create new or, if you want to update it manualy. Just please don't accept this PR. I'm sorry for troubles.

**Comment by jakubknejzlik** [comment]
It's all just about [this line](https://github.com/jakubknejzlik/VirtualGameController/commit/cb8ed95e6d5784554f1ee3df9b7b3af289963e3d#diff-4f03298f39e90a28740fa7fc578ff8c0R30)

**Comment by robreuss** [comment]
Great, I'll just make that change.  FYI, this a wiki page on using custom elements in case you didn't see it:
https://github.com/robreuss/VirtualGameController/wiki/Custom-Elements

Let me know if you notice any errors.  Can you tell me in general terms how you're using custom elements, just so I can get a feel for use cases?

**Comment by jakubknejzlik** [comment]
Well, I've copied it from example :). Also when I've specified nil value for customElements and customMappings, the app crashes right after peripheral (ios in my case) controller gets connected.

**Comment by robreuss** [comment]
Yeah, I tried setting things up to allow nil for those parameters but it was seeming like a pain, so I created an alternative startAs method in VgcManager that doesn't take those parameters, and initializes them using the superclass, which has the net effect of creating an empty set of elements/mappings:

``` swift
    public class func startAs(appRole: AppRole, appIdentifier: String) {
        VgcManager.startAs(appRole, appIdentifier: appIdentifier, customElements: CustomElementsSuperclass(), customMappings: CustomMappingsSuperclass())
    }
```

**Comment by jakubknejzlik** [comment]
Ah, I see...ok then:) ... btw you can also create it this way:

```
public class func startAs(appRole: AppRole, appIdentifier: String, customElements: CustomElements = CustomElements(), customMappers: CustomMappers = CustomMappers()) {
...
```

**Pull request closed without merging**
